FROM rust:1.72-bookworm as builder
WORKDIR /app
RUN apt update && apt install protobuf-compiler -y
COPY Cargo.toml Cargo.lock metadata.scale ./
COPY src ./src
RUN cargo build --release

FROM docker.io/library/debian:stable-slim
RUN apt update && apt install -y openssl ca-certificates libssl-dev
COPY --from=builder /app/target/release/opendid /app/opendid
COPY ./login-frontend/dist /srv
VOLUME /app/config.yaml

CMD [ "/app/opendid", "--config", "/app/config.yaml"]
