name: Check Demo Project
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo-project

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Configure Node and package manager
        uses: actions/setup-node@v3.6.0
        with:
          node-version-file: "demo-project/package.json"
          cache: "yarn"
          cache-dependency-path: "demo-project/yarn.lock"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linter
        run: yarn lint

      - name: Build code
        run: yarn build
