on:
  workflow_dispatch:
    types: [ created ]
  push:
    branches:
      - main
      - feature/ci-cd-workflow # for testing

name: Build container image

jobs:
  deploy:
    name: Build images and publish them
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build image
      run: |
        make images

    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.REPO_ACCESS_TOKEN }}
      run: |
        echo -n $DOCKER_PASS | podman login -u $DOCKER_USER --password-stdin docker.io

    - name: Tag and push image
      env:
        REGISTRY: kiltprotocol
        REPOSITORY_BASE: opendid
        IMAGE_TAG: ${{ github.sha }}
      run: |
        podman tag quay.io/kilt/simple-auth-relay-app ${REGISTRY}/${REPOSITORY_BASE}:${IMAGE_TAG}
        podman tag quay.io/kilt/simple-auth-relay-app-demo ${REGISTRY}/${REPOSITORY_BASE}-demo:${IMAGE_TAG}
        podman tag quay.io/kilt/simple-auth-relay-app-setup ${REGISTRY}/${REPOSITORY_BASE}-setup:${IMAGE_TAG}
        podman tag ${REGISTRY}/${REPOSITORY_BASE}:${IMAGE_TAG} ${REGISTRY}/${REPOSITORY_BASE}:latest
        podman tag ${REGISTRY}/${REPOSITORY_BASE}-demo:${IMAGE_TAG} ${REGISTRY}/${REPOSITORY_BASE}-demo:latest
        podman tag ${REGISTRY}/${REPOSITORY_BASE}-setup:${IMAGE_TAG} ${REGISTRY}/${REPOSITORY_BASE}-setup:latest
        podman push ${REGISTRY}/${REPOSITORY_BASE}:${IMAGE_TAG}
        podman push ${REGISTRY}/${REPOSITORY_BASE}-demo:${IMAGE_TAG}
        podman push ${REGISTRY}/${REPOSITORY_BASE}-setup:${IMAGE_TAG}
        podman push ${REGISTRY}/${REPOSITORY_BASE}:latest
        podman push ${REGISTRY}/${REPOSITORY_BASE}-demo:latest
        podman push ${REGISTRY}/${REPOSITORY_BASE}-setup:latest