name: Check gen-did script
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scripts/gen-did

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Configure Node and package manager
        uses: actions/setup-node@v3.6.0
        with:
          node-version-file: "scripts/gen-did/package.json"
          cache: "yarn"
          cache-dependency-path: "scripts/gen-did/yarn.lock"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build code
        run: yarn build
